language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install -r requirements-${TRAVIS_PYTHON_VERSION}.txt
  - pip install coveralls
  - pip install coverage
script:
  - PYTHONPATH=. coverage run -m nose2.__main__
after_success:
  - coveralls