language: python
python:
  - "2.7"
install:
  - pip install httplib2
  - pip install coveralls
  - pip install coverage
script:
  - PYTHONPATH=. coverage run -m nose2.__main__
after_success:
  - coveralls