language: python
python:
  - '2.7'
  - 'pypy'
install:
    - pip install -r requirements.txt
    - pip install httplib2
    - pip install coverage coveralls nose responses

script: nosetests --with-coverage --cover-package=testserver

after_success: coveralls
